[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Tejas-117", email = "tejasftw117@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.141.1",
]

[project.scripts]
backend = "src.app:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "src"
module-root = ""
