"""Offline tests for the complete vector-search and hydration service."""

from typing import Any

import pytest

from backend.embedding.models import (
    EmbeddingBatch,
    EmbeddingInputPurpose,
    VectorSearchHit,
)
from backend.pipeline.configs import EmbeddingConfig, RetrievalConfig
from backend.retrieval.service import (
    InvalidRetrievalArtifactError,
    retrieve_chunks,
)


class FakeEmbeddingProvider:
    """Return one deterministic query vector and record provider inputs."""

    identifier = "test-provider"
    version = "1"

    def __init__(self) -> None:
        """Initialize an empty record of query embedding calls.

        Args:
            None.

        Returns:
            None. Calls begin empty for later assertions.
        """
        self.calls: list[tuple[str, list[str], EmbeddingInputPurpose]] = []

    def input_policy_version(self, model: str) -> str:
        """Return the input policy expected by the compatible test index.

        Args:
            model: Provider model selected by the retrieval configuration.

        Returns:
            Stable test input-policy identity.
        """
        return "test-policy-v1"

    def embed(
        self,
        model: str,
        texts: list[str],
        purpose: EmbeddingInputPurpose,
    ) -> EmbeddingBatch:
        """Record the request and return one fixed three-dimensional vector.

        Args:
            model: Provider model selected for the query.
            texts: Normalized one-question embedding input.
            purpose: Semantic query role supplied to the provider.

        Returns:
            Deterministic query embedding batch.
        """
        self.calls.append((model, texts, purpose))
        return EmbeddingBatch(vectors=((1.0, 2.0, 3.0),), dimensions=3)


class FakeVectorStore:
    """Return deterministic lightweight vector hits and record the search."""

    identifier = "test-store"
    version = "1"

    def __init__(self, hits: tuple[VectorSearchHit, ...]) -> None:
        """Configure the vector hits returned by the fake adapter.

        Args:
            hits: Ranked lightweight vector matches returned by query.

        Returns:
            None. Calls begin empty for later assertions.
        """
        self.hits = hits
        self.calls: list[tuple[str, list[float], int]] = []

    def query(
        self,
        collection_name: str,
        vector: list[float],
        top_k: int,
    ) -> tuple[VectorSearchHit, ...]:
        """Record one nearest-neighbor query and return configured hits.

        Args:
            collection_name: Exact compatible collection being searched.
            vector: Query vector generated by the embedding provider.
            top_k: Result limit clamped to the index vector count.

        Returns:
            Configured lightweight vector hits.
        """
        self.calls.append((collection_name, vector, top_k))
        return self.hits


def _embedding_config() -> EmbeddingConfig:
    """Create the embedding configuration used by retrieval service tests.

    Args:
        None.

    Returns:
        Valid embedding configuration matching the fake index.
    """
    return EmbeddingConfig(
        provider="ollama",
        model="nomic-embed-text",
        distance_metric="cosine",
    )


def _vector_index(**overrides: Any) -> dict[str, Any]:
    """Create one complete compatible vector index with optional overrides.

    Args:
        overrides: Index fields replacing compatible test defaults.

    Returns:
        Ready vector-index dictionary accepted by the retrieval service.
    """
    vector_index = {
        "id": "vector-index-1",
        "chunk_set_id": "chunk-set-1",
        "status": "ready",
        "provider": "ollama",
        "model": "nomic-embed-text",
        "distance_metric": "cosine",
        "input_policy_version": "test-policy-v1",
        "indexer_name": "test-store",
        "indexer_version": "1",
        "collection_name": "rag_idx_test",
        "dimensions": 3,
        "vector_count": 2,
    }
    vector_index.update(overrides)
    return vector_index


def _chunk(chunk_id: str, ordinal: int, text: str) -> dict[str, Any]:
    """Create one materialized immutable chunk returned by the test loader.

    Args:
        chunk_id: Stable chunk identifier requested by hydration.
        ordinal: Zero-based chunk order in its source document.
        text: Exact embedded text owned by the chunk.

    Returns:
        Complete chunk dictionary matching the hydration boundary.
    """
    return {
        "id": chunk_id,
        "source_document_id": "document-1",
        "ordinal": ordinal,
        "text": text,
        "character_start_offset": ordinal * 10,
        "character_end_offset": (ordinal + 1) * 10,
        "token_start_offset": ordinal * 2,
        "token_end_offset": (ordinal + 1) * 2,
        "page_start": ordinal + 1,
        "page_end": ordinal + 1,
        "section_path": None,
        "source_metadata": {"block_ordinals": [ordinal]},
    }


def test_retrieve_chunks_searches_then_hydrates_in_rank_order() -> None:
    """Verify the service coordinates query embedding, search, and hydration.

    Args:
        None.

    Returns:
        None. Assertions cover dependency inputs and fully hydrated ordering.
    """
    provider = FakeEmbeddingProvider()
    vector_store = FakeVectorStore(
        (
            VectorSearchHit("chunk-2", 0.1),
            VectorSearchHit("chunk-1", 0.2),
        )
    )
    chunks = {
        "chunk-1": _chunk("chunk-1", 0, "First"),
        "chunk-2": _chunk("chunk-2", 1, "Second"),
    }
    loader_calls: list[tuple[str, tuple[str, ...]]] = []

    # The injected loader records artifact scoping without touching SQLite.
    def load_chunks(
        chunk_set_id: str,
        chunk_ids: tuple[str, ...],
    ) -> dict[str, dict[str, Any]]:
        """Return requested test chunks and record the scoped batch lookup.

        Args:
            chunk_set_id: Exact chunk set supplied by the vector index.
            chunk_ids: Ranked stable IDs returned by vector search.

        Returns:
            Requested chunk records keyed by stable ID.
        """
        loader_calls.append((chunk_set_id, chunk_ids))
        return {chunk_id: chunks[chunk_id] for chunk_id in chunk_ids}

    hydrated = retrieve_chunks(
        "  What changed?  ",
        RetrievalConfig(top_k=10),
        _embedding_config(),
        _vector_index(),
        provider,
        vector_store,
        load_chunks,
    )

    assert provider.calls == [
        (
            "nomic-embed-text",
            ["What changed?"],
            EmbeddingInputPurpose.QUERY,
        )
    ]
    assert vector_store.calls == [("rag_idx_test", [1.0, 2.0, 3.0], 2)]
    assert loader_calls == [("chunk-set-1", ("chunk-2", "chunk-1"))]
    assert [(hit.rank, hit.chunk_id, hit.text) for hit in hydrated] == [
        (1, "chunk-2", "Second"),
        (2, "chunk-1", "First"),
    ]


def test_retrieve_chunks_allows_empty_search_results() -> None:
    """Verify no-hit vector searches return an empty hydrated result.

    Args:
        None.

    Returns:
        None. Assertions verify the chunk loader is not called.
    """
    provider = FakeEmbeddingProvider()
    vector_store = FakeVectorStore(())

    # A failing loader proves hydration short-circuits empty search results.
    def unexpected_loader(
        chunk_set_id: str,
        chunk_ids: tuple[str, ...],
    ) -> dict[str, dict[str, Any]]:
        """Fail if an empty vector result attempts a database lookup.

        Args:
            chunk_set_id: Unused artifact identifier.
            chunk_ids: Unused empty chunk identifier tuple.

        Returns:
            No return is expected because the function always fails.
        """
        raise AssertionError("The chunk loader should not be called.")

    hydrated = retrieve_chunks(
        "Question",
        RetrievalConfig(top_k=2),
        _embedding_config(),
        _vector_index(),
        provider,
        vector_store,
        unexpected_loader,
    )

    assert hydrated == ()


def test_retrieve_chunks_rejects_missing_chunk_set_before_search() -> None:
    """Verify an index without hydration provenance fails before provider work.

    Args:
        None.

    Returns:
        None. Assertions verify the provider and vector store remain unused.
    """
    provider = FakeEmbeddingProvider()
    vector_store = FakeVectorStore(())

    with pytest.raises(InvalidRetrievalArtifactError, match="chunk-set"):
        retrieve_chunks(
            "Question",
            RetrievalConfig(top_k=2),
            _embedding_config(),
            _vector_index(chunk_set_id=""),
            provider,
            vector_store,
        )

    assert provider.calls == []
    assert vector_store.calls == []
